sudo: false
language: ruby
services:
  - docker
before_install:
  - git clone --depth 1 https://github.com/seiferma/Docker_BuildUtils.git /tmp/BuildUtils
  - . /tmp/BuildUtils/travisSetup.sh
script:
  - travisBuild.sh
deploy:
  provider: script
  script: travisDeploy.sh
  on:
    branch: master
env:
  global: 
    - IMAGE_NAME=seiferma/tvheadend
    - secure: "TXfQDN3n8uGl/OIfZ4vpKmQOJ4ABePcdF0rD6nxDKNloPP5lA4JWUV+RIbBfcnONuRk4Np0IL7FxCGRewcu/TQp2qUXUWZGC/cCgtih1IMrh10DMbCehJbVBTnOpuJj0GXthxA8pYVj6/17Ac5Kz+N9AVibkEY8sRkB2LvITPpR3p8UwB2zSkyTRa+WXPvxDFded1JJUSU+q4hI7ZqZ2hVRFqQ5kbCNPMMBi+QEEoK3CEt84j4DBf1LlmRGOs0JlIIC/xyz2wcL4sNXnegQhwiSRYNa7wKvK07tNqfScCyhvVUxi9y9OpLYtN3iFqBhUur4K9RZ5Ti3Ab2r7CB/5rtxRegjG/ofrtI+B+ONSqHiSfkDpebGqkQDBWo+mHFDM0ZolftmXiOi+ed11ThAzOXjJTRaSGwLo/PQJV6OY07Sc32IJxIWdAQsU/8K7TytpLJvwQYARnNOfmgOYrf5/gJwB/bnuwU+ugob4dhl7OMhXcJGG9oPN4GnCxBsYVEyMrdXabIJHKRqibW4KERSmon8wvGRyzVCAHdPxAnPWJ/UQ2U+h+fO2vQjt5DGIDIDNnWRIlSz8EXVJJOU/g/4U7+3e+cK6GhTugKk1ebqbe4zbyB2C4dQkFlynqTWL7eGcvJnlh5huja420n8ZXiJTrrvbdxjKgTxIvtyXeZ4P/Vw="